# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "M_sort"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2021, John S. Urban"
description = "sorting procedures"
categories = ["sorting"]
keywords = ["fortran", "quick sort"]
homepage = "https://github.com/urbanjost/M_sort.git"

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dev-dependencies]
M_strings = { git = "https://github.com/urbanjost/M_strings.git" }
M_io = { git = "https://github.com/urbanjost/M_io.git" }
M_CLI2 = { git = "https://github.com/urbanjost/M_CLI2.git" }
M_sort = { git = "https://github.com/urbanjost/M_sort.git" }


[[test]]
name="test_suite_M_sort"
source-dir="test"
main="test_suite_M_sort.f90"
[test.dependencies]
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
